### ISSUE TITLE
Examples: Update documentation and support files for examples to account for new deployment documentation

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#152]
# Definition of Done
- [ ] Documentation landing page for examples
- [ ] Documentation updated to point to deployment documentation
- [x] Spurious files removed

READMEs answer the question of "What do I do next?"
Documentation of example will walk a user through the particulars of an example. Tutorial of the example.
Documentation page for examples will describe how to accomplish a particular task or set of tasks or describes the nature of examples/plugins/etc..

### Prerequisites Setup

1. point to deployment instructions
    - (mention cpu/gpu distinction)
2. point to dataset download instructions
3. Instructions for mounting datasets for a local/single machine installation
    - point to more general instruction.
5. Instructions for minimal python env/dependencies (point to script)
6. Usage Instructions
    - (port make file to python script)

### Table Summarizing Example
Dataset used (prereq)
GPU needed? (prereq)
What does it show? Attacks/ Defenses (info)
ML Librrary? pytorch/tensorflow (info)
architecture (info)

## Each of the examples is updated:

- [x] pytorch-detectron2-demo
- [x] pytorch-mnist-membership-inference
- [x] tensorflow-adversarial-patches
- [x] tensorflow-backdoor-poisoning
- [x] tensorflow-imagenet-pixel-threshold
- [x] tensorflow-imagenet-resnet50-fgm
- [x] tensorflow-mnist-classifier
- [x] tensorflow-mnist-feature-squeezing
- [x] tensorflow-mnist-model-inversion
- [x] tensorflow-mnist-pixel-threshold

## These examples are marked for deletion

- [x] basic-mlflow-demo
- [x] patch-defended-pixel-threshold
- [x] pytorch-robust-dpatch
- [x] tensorflow-roadsigns-yolo

### Tasks for each example
- Task plugins go into common folder under examples directory
- Script to register all task plugins
- rename to avoid collisions and indicate example
- move MLproject files to src and remove use of relative path to src
- Delete extraneous files
    - init.db
    - environment.yml
    - architecture diagram
    - utils.py
    - /data subdir
    - /jupyter subdir
- simplify notebooks to focus only on example
- remove any descriptions of dataset

**Comment by jkglasbrenner** [comment]
_Originally posted by @jkglasbrenner in https://github.com/usnistgov/dioptra/issues/19#issuecomment-1462671488_

Figured it out, the 403 - Forbidden error appears if you don't agree to the competition rules (even though the competition is over). At the bottom of <https://www.kaggle.com/competitions/imagenet-object-localization-challenge/data>, you'll see this:

![image](https://user-images.githubusercontent.com/8547754/224135609-aca1823b-bb80-4d70-bf70-5db6da5f1b4f.png)

People need to sign-in using the account they used to generate the Kaggle API token, and then the "Sign In" will be replaced with I Accept/I Agree. Once you agree, that box gets replaced with:

![image](https://user-images.githubusercontent.com/8547754/224136267-2e3bc549-a088-4139-a19b-360a7ea0e013.png)

Now if you try to download using the kaggle CLI tool, it will work (provided you remember to generate the API token).
