### ISSUE TITLE
Expand functionality of task plugin REST endpoints

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#241]
The current implementation scans Minio S3 object storage for the existing plugins and does not persist any information about the plugins in the database. To incorporate metadata with the plugins, we need to create database entries for the plugins and tie it to their storage location.

## Design Spec

For this redesign, the plugin files will still be uploaded to the REST API, but now each individual Python file will be stored in a flat folder. Each Python file is assigned a UUID, and the database will provide the necessary information to translate the UUID filenames to a fully-qualified Python path (i.e. `collection_name.file_name.plugin_name`).

The following new tables are need to be created to support this new functionality.

**Task Plugins table**

| id | output_type_id | file_id | name |
| --- | --- | --- | --- |
| | | | |

**Task Plugin Files table**

| id | collection_id | filename |
| --- | --- | --- |
| | | |

**Task Plugin Collection table**

| id | name |
| --- | --- |
| | |

**Task Plugin Parameters table**

| id | plugin_id | type_id | name |
| --- | --- | --- | --- |
| | | | |

**Task Plugin Tags linking table**

| plugin_id | tag_id |
| --- | --- |
| | |

When a new job starts, it will request the plugins from a task plugin endpoint. The API will lookup the plugin information in the database and use that to fetch the files. It will then rename and reorganize the files to provide the proper folder structure, zip it up, and provide it as a download. The worker container will then use the Dioptra Client to download the zip and unpack it.

## Definition of Done

- [ ] The above tables are implemented in the database
- [ ] The plugin registration process called using the REST API endpoints is expanded to accept the new information, and populate the tables using the plugin collection folder structure.
- [ ] Task plugin endpoints are extended to allow the GUI to retrieve the expanded metadata.
- [ ] The endpoints are extended to allow the client to download the latest versions of the plugins via the API (currently this is just a direct S3 sync).
- [ ] The Dioptra Client is updated to make use of this new functionality.

**Comment by keithmanville** [comment]
stale
