### ISSUE TITLE
Visualize artifacts in the Dioptra UI

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#572]
Add support for visualizing artifacts in the Dioptra UI.

We would like to be able to visualize plain text files and images. Other binaries (e.g. model weights) should offer a download option.

### Tasks:
- [ ] Define and document types of artifacts which can be visualized
- [ ] Document new API endpoints for browsing and retrieving artifact files
- [ ] Implement new API endpoints for browsing and retrieving artifact files
- [ ] Implement visualization of artifacts in the UI
