### ISSUE TITLE
Make the Dioptra install and configuration process as simple as possible

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#584]
Make the Dioptra install and configuration process as simple as possible.

### Tasks:
- [ ] Implement our own GitHub runners to enable signing of docker images using cosign
- [ ] Reconfigure and expand GitHub action workflows to use the new runners and sign images
- [ ] Update the cookiecutter template to pull images from the docker registry by default
- [ ] Implement dioptra command line tool to configure and install Dioptra
- [ ] Reconfigure GitHub action workflows to build, sign, and register Dioptra package
- [ ] Update documentation with new setup instructions

### Definition of done:
- [ ] The user is able to run a single command so that upon completion the user has an installed single-machine deployment of Dioptra with a working example.
