### ISSUE TITLE
As a plugin developer I want to be able to import and sync plugins in order to develop and manage plugins externally

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#586]
Add functionality to import and sync plugins from external sources. This functionality will be used to manage Dioptra provided plugins as well as third party plugins.

Initially, the only option for a synchronization source will be a git repository. Other sources can be considered in the future.

### Tasks:
- [ ] Design and document a contract for the structure of a Dioptra plugin
- [ ] Add a workflow for importing a plugin from a git repository
- [ ] Add a workflow for syncing a plugin from a git repository
- [ ] Create a simple "hello-world" plugin
- [ ] Add deployment configuration options for default plugins and make the "hello-world" plugin a default
- [ ] Add new UI elements to enable plugin import functionality to the frontend
- [ ] Add new UI elements to enable plugin sync functionality to the frontend
