### ISSUE TITLE
Add a workflow for importing a plugin from a git repository or file upload

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#588]
We want to support the importing of plugins from external sources. This allows for:
- External development of plugins
- Sharing of plugins between deployments
- Management and automatic registration of Dioptra built-in plugins
- Automated registration of plugins (instead of manually uploading each file via a client)

This will be implemented as a new workflow in the REST API, `/workflows/resourcesImport`.

Initially, all imported plugins will have a read-only lock applied. We will consider mechanisms for editing and reconciling changes in the future.

Initially, we will support importing from a archive (.zip, or .tar.gz) file upload or a git repository (no authentication support). We will consider other sources in the future.

A new database table to track import source will be needed. It should include: id, name, source_type, url, hash, and timestamp(s).

### Tasks:
- [x] Design the schemas and endpoint(s) for the `resourcesImport` workflow in the REST API design doc on google drive
- [x] Add the design to this issue once finalized
- [x] Implement the schema(s) and controller(s) for the workflow
- [ ] Add new database table for tracking import source
- [x] Implement the service layer with a single database commit
- [x] Write documentation for the structure of an importable plugin

### Definition of Done:
- [x] The contract for the structure of a plugin is documented in the sphinx docs
- [x] Plugins can be imported from a file upload or git repository via a workflow
- [ ] New integration tests that cover plugin import functionality are implemented
- [ ] All tests pass
- [ ] The feature is merged into dev

**Comment by keithmanville** [comment]
A workflow for importing resources from a file or git repo. It will handle the importing of the following resources:
- Plugin
- PluginFile
- PluginParameterType
- EntryPoint

`POST /workflows/resourcesImport`
payload:
```python
{
  "groupId": int,  # the group that will own the imported resources
  "sourceType": Enum("upload", "git"),  # the source of the import
  "uri": str | None,  # the uri of the git repository (if sourceType is git)
  "data": bytes | None,  # the uploaded archive file (if sourceType is upload)
  "readOnly": bool,  #  whether imported resources should get a readonly lock
  "resolveNameConflicts", Enun("fail", "overwrite")  # behavior for resolving name conflicts
}
```
