### ISSUE TITLE
Add endpoints for storing and retrieving metrics

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#675]
Add new endpoints for storing and retrieving metrics. The service layer should proxy the calls to the mlflow client.

This is part of an effort to completely hide mlflow from the user.

### Tasks:
- [x] Design the schemas and endpoint(s) for the `metrics` endpoint in the REST API design doc on google drive
- [x] Implement the schema(s) and controller(s) for the endpoint
- [x] Implement the service layer 
- [x] Write new tests for the metrics endpoints

### Definition of Done:
- [x] The new endpoints are documented in the API design doc on google drive
- [x] Metrics can be created and retrieved
- [ ] New integration tests that cover the metrics functionality are implemented
- [x] All tests pass
- [x] The feature is merged into dev
