### ISSUE TITLE
Update UI to indicate when a plugin attached to an entrypoint is out-of-date

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#677]
We want the UI to indicate when a plugin attached to an entrypoint is out-of-date and provide a mechanism to sync to the latest version of plugins.

To do this, we need to update relationships between Entrypoints, Plugins, and Plugin files enable Entrypoint to Plugin syncing behavior.

### Tasks
- [x] Split the EntryPointPluginFiles table into two many-to-many linking tables: EntrypointPlugins and PluginPluginFiles
- [x] Create new database migration scripts
- [ ] Update [EntrypointService.create](https://github.com/usnistgov/dioptra/blob/4a77125659a05ac6817eff9a7c24ae9d662019e8/src/dioptra/restapi/v1/entrypoints/service.py#L148), [EntrypointIdService.modify](https://github.com/usnistgov/dioptra/blob/4a77125659a05ac6817eff9a7c24ae9d662019e8/src/dioptra/restapi/v1/entrypoints/service.py#L470), [EntrypointIdPluginsService.append](https://github.com/usnistgov/dioptra/blob/4a77125659a05ac6817eff9a7c24ae9d662019e8/src/dioptra/restapi/v1/entrypoints/service.py#L645), and [EntrypointIdPluginFilesId.delete](https://github.com/usnistgov/dioptra/blob/4a77125659a05ac6817eff9a7c24ae9d662019e8/src/dioptra/restapi/v1/entrypoints/service.py#L804) services to use the new EntryPointPlugin linking table
- [ ] Update [build_entrypoint](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/v1/utils.py#L584) to use the new EntrypointPlugin linking table to retrieve plugin information
- [ ] Update the [PluginIdService.modify](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/v1/plugins/service.py#L379) service to create `PluginPluginFiles` entries for the new snapshot
- [ ] Add a mapped_column to [Plugin](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/db/models/plugins.py#L35) that retrieves linked `PluginFile` snapshots
- [ ] Update the [PluginIdService.get](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/v1/plugins/service.py#L351) and all other `get` services in `plugins.py` to retrieve latest `PluginFile` snapshots from the `PluginPluginFile` linking table instead of via separate query 
- [ ] Update any services that create, modify, or delete a `PluginFile` to create a new `Plugin` Snapshot that is properly linked to `PluginFiles` via the new `PluginPluginFiles` table
- [ ] Remove the `plugin_files` key from  [PluginWithPluginFIlesDict](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/v1/utils.py#L71) and rename it `PluginDict`
- [ ] Update [build_entrypoint_plugin](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/v1/utils.py#L242) and [build_plugin](https://github.com/usnistgov/dioptra/blob/6078bce83168cc9f6ba5a61ba3d7f30d5c662679/src/dioptra/restapi/v1/utils.py#L804) to use new `PluginDict` class
- [ ] Update all service layer use of `PluginWithFilesDict` to use `PluginDict` (primarily as return types of functions)
- [ ] Update the UI to indicate when a plugin is out of date (this should check Plugin.latestSnapshot)
- [ ] Update the UI to provide a button to sync plugins to the latest version (this should use POST to /entrypoints/{id}/plugins)

### Definition of done
- [ ] All tasks are implemented
- [ ] All tests pass
- [ ] Feature is merged to dev
